version: '3.7'

networks:
  childlanglab:
    name: ${LABMEMBER_NAME}_local

services:
  webserver:
    build: 
      ./conf/nginx/
    container_name: ${LABMEMBER_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./experiments:/var/www/html:delegated
      - ./certs/:/etc/nginx/ssl
    depends_on:
      - php
      - postgres
    networks:
      - childlanglab

  php:
    build:
      ./conf/php/
    container_name: ${LABMEMBER_NAME}_php
    volumes:
      - ./experiments:/var/www/html:delegated
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TABLE=${DB_TABLE}
      - DB_SSLMODE=${DB_SSLMODE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    ports:
      - "9000:9000"
    networks:
      - childlanglab

  postgres:
    image: postgres:10
    command: ["postgres", "-c", "log_statement=all"]
    container_name: ${LABMEMBER_NAME}_postgres
    restart: unless-stopped
    tty: true
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=postgres
    networks:
      - childlanglab
  